# Generated by Django 2.1.7 on 2019-04-22 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='カテゴリ名')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='お名前')),
                ('text_comment', models.TextField(max_length=200, verbose_name='本文')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='FreePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=16, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=8, verbose_name='パスワード')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入日')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='キャッチコピーの文章です。12文字まで', max_length=12, verbose_name='キャッチコピー')),
                ('pre_text', models.TextField(default='本来のタイトルです。100文字まで。', max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(default='本文', max_length=2000, verbose_name='本文')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='カテゴリー')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.FreePoster', verbose_name='投稿者')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='関連コメント'),
        ),
    ]
