# Generated by Django 2.1.7 on 2019-04-22 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StablePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_text', models.TextField(default='本来のタイトルです。100文字まで。', max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(default='本文', max_length=2000, verbose_name='本文')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.FreePoster', verbose_name='投稿者')),
            ],
        ),
    ]
